En JavaScript, la palabra clave `async` introduce una forma más sencilla y limpia de trabajar con operaciones asíncronas, permitiendo escribir código asíncrono que parece sincrónico o secuencial. Las funciones marcadas con `async` siempre retornan una promesa, lo que facilita la gestión del flujo asíncrono.

#### Definición de una Función Asíncrona

Una función se define como asíncrona al anteponer la palabra clave `async` antes de la declaración de la función. Puede ser una función declarada, una expresión de función, o un método de clase.

**Ejemplo de Función Asíncrona:**

javascript

Copiar código

`async function hacerAlgo() {     return "Hecho"; }`

Aunque el cuerpo de la función `hacerAlgo` no parece contener nada asíncrono y simplemente retorna un string, JavaScript automáticamente envuelve ese valor en una promesa. Esto significa que puedes usar `.then()` con el resultado de `hacerAlgo()`:

javascript

Copiar código

`hacerAlgo().then(resultado => console.log(resultado));  // "Hecho"`

#### Esperando Promesas con `async`

La verdadera utilidad de las funciones `async` se manifiesta cuando se combina con la palabra clave `await`, que sólo puede usarse dentro de funciones `async`. `await` pausa la ejecución de la función hasta que la Promesa a la que se está esperando se resuelve o rechaza.

**Ejemplo con `await`:**

javascript

Copiar código

`async function obtenerDatos() {     const respuesta = await fetch('https://api.example.com/data');     const datos = await respuesta.json();     return datos; }  obtenerDatos().then(datos => console.log(datos));`

En este ejemplo, `obtenerDatos` hace una solicitud a una API y espera a que se complete antes de convertir la respuesta a JSON y luego retornar esos datos. Todo esto se hace de manera que el código se lee y se escribe de una forma casi secuencial, lo cual es mucho más fácil de seguir que las cadenas de promesas o los callbacks anidados.

#### Manejo de Errores en Funciones Asíncronas

El manejo de errores en funciones asíncronas se puede hacer utilizando bloques `try...catch`. Esto te permite capturar errores en operaciones asíncronas de la misma manera que capturarías errores en operaciones sincrónicas.

**Ejemplo de Manejo de Errores:**

javascript

Copiar código

`async function obtenerDatosSeguros() {     try {         const respuesta = await fetch('https://api.example.com/data');         if (!respuesta.ok) {             throw new Error('Error al obtener los datos');         }         const datos = await respuesta.json();         return datos;     } catch (error) {         console.error('Error:', error);     } }  obtenerDatosSeguros().then(datos => {     if (datos) {         console.log(datos);     } });`


---
![[Pasted image 20240516145409.png]]
